set complete-=k complete+=k
set dictionary-=E:\Vim\dic.txt dictionary+=E:\Vim\dic.txt
syntax on
set fenc=utf-8  "fileencodings的简写   默认编码
set fencs=utf-8,ucs-bom,gb18030,gbk,gb2312,cp936

"  以下四个命令代码缩进相关
set expandtab   "tab都用空格代替
set softtabstop=4  "tab=四个空格
set tabstop=4
set autoindent  "继承前一行的缩进

set nocompatible "不兼容vi的键盘模式
set ruler  "在状态行显示光标所在位置的行号和列号
set nu
"不生成临时文件
set noswapfile
set nobackup


set ignorecase  "搜索忽略大小写

"自动补全括号
:inoremap ( ()<Esc>i   
:inoremap { {}<ESC>i
:inoremap [ []<ESC>i 
